name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 35
        build-tools-version: 35.0.0
        ndk-version: 27.2.12479018

    - name: Make gradlew executable
      run: chmod +x .HelloWorldCompose/gradlew

    - name: Build Release APK
      run: ./HelloWorldCompose/gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk

